### ISSUE TITLE
wav.pm

### ISSUE THREAD

**Issue by forggles** [iafan/Hacksby#2]
I was trying to use the scripts you wrote but I keep running into this error
any idea how to fix it?

Can't locate Audio/Wav.pm in @INC (@INC contains: C:\Users\Barbara\Desktop\Hacks
by\lib C:/Perl64/site/lib C:/Perl64/lib .) at C:\Users\Barbara\Desktop\Hacksby\l
ib/Furby/Audio.pm line 7.
BEGIN failed--compilation aborted at C:\Users\Barbara\Desktop\Hacksby\lib/Furby/
Audio.pm line 7.
Compilation failed in require at furby-send.pl line 13.
BEGIN failed--compilation aborted at furby-send.pl line 13.

**Comment by iafan** [comment]
You need to install the missing `Audio::Wav` dependency module. See http://search.cpan.org/~brianski/Audio-Wav/

The easiest way to do this is to say:

`sudo cpan Audio::Wav` in the command line.
