### ISSUE TITLE
Sintax error

### ISSUE THREAD

**Issue by Yottaqubyter** [iafan/Hacksby#5]
There is a bug in the sintax, in line 13:
Can't locate Audio/Wav.pm in @INC (you may need to install the Audio::Wav module) (@INC contains: /c/Users/Mario Jiménez/Documents/GitHub/Hacksby/bin/../lib /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /c/Users/Mario Jiménez/Documents/GitHub/Hacksby/bin/../lib/Furby/Audio.pm line 7.
BEGIN failed--compilation aborted at /c/Users/Mario Jiménez/Documents/GitHub/Hacksby/bin/../lib/Furby/Audio.pm line 7.
Compilation failed in require at furby-send.pl line 13.
BEGIN failed--compilation aborted at furby-send.pl line 13.

**Comment by iafan** [comment]
`sudo cpan Audio::Wav` should install the missing dependency.
